### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by archaistvolts** [tomhoule/zig-diff#2]
This is a neat implementation of diff match patch :+1:.  I like that it uses ranges which can be merged without any allocations. I think this makes it more memory efficient than other implementations of diff match patch i've looked at - IE google diff match patch and sergi/go-diff.  Would you agree? 

I'm looking into the possibility of using this implementation in zigtools/zls which recently added diffing support in order to speed up formatting large files. The [new code](https://github.com/ziglibs/diffz/blob/f25b31c4f8d06bc134018133a2d57b6dcbb6941e/DiffMatchPatch.zig) is a port of google's diff match patch to zig. But I believe it has performance and stability issues which are likely related to its memory usage.  

Thus I wanted to see if this implementation performs any better.  And that is why I'm asking to add a license to this project.  If you decide to add one, and want it to be compatible, zls has an MIT license. So any compatible license would work.  Thanks for considering this and thanks for sharing this code :pray:.

**Comment by tomhoule** [comment]
Hi @travisstaloch , thanks for your interest. I think this library would need more love in order to be really usable, this was more of a learning project for me. I wanted to lead with that caveat.

That said, if you really want to give it a try, I can offer to 1. add a license file (MIT/Apache v2 is what I usually use, but happy to take feedback), 2. review PRs, 3. make interested people maintainers on this repo.

**Comment by archaistvolts** [comment]
Great! I'm glad to hear it.  MIT/Apache v2 sounds good. :+1: 

I'll sit down soon and look at whats missing for this to be usable in zls. Perhaps semantic cleanups as you mention in the readme - although i'm not sure its necessary as the diffs don't need to be human readable, just fast.

Let me know if you have any thoughts on whats missing and/or what to focus on.

**Comment by tomhoule** [comment]
I quickly opened a PR from the github UI here: https://github.com/tomhoule/zig-diff/pull/3

It's only Apache v2 because GitHub doesn't make it easy to dual license (that would be my preference). We can either merge this if that sounds fine for you or wait until I find the time to do the dual licensing properly.

**Comment by archaistvolts** [comment]
Thanks! Yes that looks good to me :eyes:

**Comment by tomhoule** [comment]
The PR with the license is merged now, I think we can close this issue. I'm here if anything else comes up :)

**Comment by archaistvolts** [comment]
Thanks for adding the license. Just FYI, I don't think I'll actually be working with this lib yet. I've been looking at dissimilar and want to try the port from scratch myself.  Will let you know how it goes here.  Could be bad, I have rust skill issues :smirk:.  And some of those testing macros look ugly.  Very glad to have your code as a reference.

**Comment by archaistvolts** [comment]
just got all the tests passing with no memory leaks, including semantic cleanups :grin: https://github.com/travisstaloch/diff-zimilar/

**Comment by archaistvolts** [comment]
If you ever have a look, let me know if you have any feedback. I'm sure there are lots of things i've forgotten and room for improvement.  I hope I've given proper credit and attribution too.
